const types = {
  system: {
    LOADING: "SYSTEM:LOADING",
    LOADED: "SYSTEM:LOADED"
  },
  calculator: {
    SWITCH: "CALCULATOR:SWITCH"
  },
  equation: {
    ALL_CLEAR: "EQUATION:ALL_CLEAR",
    RESULT: "EQUATION:RESULT",
    ERROR: "EQUATION:ERROR",
    APPEND_CHUNK: "EQUATION:APPEND_CHUNK",
    POP_CHUNK: "EQUATION:POP_CHUNK",
    NEST_CHUNKS: "EQUATION:NEST_CHUNKS",
    HOIST_CHUNKS: "EQUATION:HOIST_CHUNKS",
    SLOT_CHUNKS: "EQUATION:SLOT_CHUNKS",
    DEGREES_SWITCH: "EQUATION:DEGREES_SWITCH",
    UPDATE_EXECUTABLE: "EQUATION:UPDATE_EXECUTABLE"
  }
};

export default types;
