const types = {
  system: {
    LOADING: "SYSTEM:LOADING",
    LOADED: "SYSTEM:LOADED"
  },
  calculator: {
    SWITCH: "CALCULATOR:SWITCH"
  },
  equation: {
    ALL_CLEAR: "EQUATION:ALL_CLEAR",
    RESULT: "EQUATION:RESULT",
    ERROR: "EQUATION:ERROR",
    APPEND_CHUNK: "EQUATION:APPEND_CHUNK",
    POP_CHUNK: "EQUATION:POP_CHUNK",
    NEST_CHUNK: "EQUATION:NEST_CHUNK",
    HOIST_CHUNK: "EQUATION:HOIST_CHUNK",
    DEGREES_SWITCH: "EQUATION:DEGREES_SWITCH"
  }
};

export default types;
